name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.2.2
    - uses: cachix/install-nix-action@v30
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v15
      with:
        name: iohk
    - uses: cachix/cachix-action@v15
      with:
        name: tinybeachthor
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build generator
      run: nix build
    - name: Build blog
      run: ./result/bin/blog4

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
